### ISSUE TITLE
PHP notice in the CP

### ISSUE THREAD

**Issue by murtaugh** [MaxLazar/cp-css-js#1]
PHP notices are being thrown in the CP which I think is preventing custom JS from working.

The messages: 

```
Notice
Undefined property: Cp_css_js_ext::$ee
user/addons/cp_css_js/ext.cp_css_js.php, line 96

Notice
Trying to get property 'extensions' of non-object
user/addons/cp_css_js/ext.cp_css_js.php, line 96

Notice
Trying to get property 'last_call' of non-object
user/addons/cp_css_js/ext.cp_css_js.php, line 96
```

This is in the latest EE and PHP 7.3.27

**Comment by frshjb373** [comment]
Yes, same issue here...php ver 7.4

**Comment by robinsowell** [comment]
Does changing that line 96 from


            $data = $this->EE->extensions->last_call;
to

            $data = ee()->extensions->last_call;

Fix it?

**Comment by murtaugh** [comment]
Wow, I totally missed @robinsowell's reply and dropped the ball on this conversation, sorry about that.

I've since upgraded to PHP 8.0.2, and I no longer get the PHP errors, but the JS still doesn't work, so I guess it wasn't that :(

**Comment by robinsowell** [comment]
We're still hitting php 8 issues on occasion too.  LOT of changes on that one!  Bummer it didn't solve the issue!

**Comment by MaxLazar** [comment]
@robinsowell  could you please post what errors you have now (my local env is on php 8.0.8, 8.1.1)?
